Create main.yml
cmsc389T-spring22/Team3 pull request #37
Opened 2022-03-14 04:29 UTC by sschacko

Please review and if it's a good start, merge the feature-item to FTR-actions as per the instructions of the P4 README.md

2022-03-15 00:58 UTC, striker4150 requested changes
In addition to fixing the `javac` command, please remove the unnecessary `.github/workflows/main.yml` in the `Projects/P3/tests` directory. According to [this](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows), workflows can only be put in the root directory of the repository.

2022-03-15 00:58 UTC, striker4150 commented on .github/workflows/main.yml
> +          javac -cp "../Projects/P3/tests/junit-4.10.jar:." *.java
Keep in mind that the entire repository is checked out, so you need to compile the `.java` files in the **Projects/P3** directory.

2022-03-15 02:54 UTC, sschacko commented on .github/workflows/main.yml
> +          javac -cp "../Projects/P3/tests/junit-4.10.jar:." *.java
I think I followed what you were saying, but it still had build errors

2022-03-15 05:04 UTC, striker4150 commented on .github/workflows/main.yml
> +          javac -cp "../Projects/P3/tests/junit-4.10.jar:." *.java
See slack thread

2022-03-15 07:19 UTC, striker4150 submitted a review, later dismissed
Please delete the .class file.

2022-03-16 09:25 UTC, striker4150 approved these changes

2022-03-16 09:26 UTC, merged